classname: LightADC64EventGenerator
path: module0_flow.reco.light.adc64_event_generator
dset_name: 'light/events'
params:
  # secondary output
  wvfm_dset_name: 'light/wvfm'

  # configuration parameters
  #n_adcs: 2
  n_adcs: 1
  n_channels: 64
  sn_table:
   #- 175780172
   #- 175854781
   - 0x0cd9416d
  sync_channel: 32
  sync_threshold: 999999999 #10000
  batch_size: 128
  utime_ms_window: 1000
  tai_ns_window: 1000
